language: node_js

node_js:  
  - "node"

cache:
  directories:
    - "node_modules"
env: YARN_GPG=no   
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH